// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGcompositeOperationState {
 *     int srcRGB;
 *     int dstRGB;
 *     int srcAlpha;
 *     int dstAlpha;
 * }
 * }
 */
public class NVGcompositeOperationState {

    NVGcompositeOperationState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NVG.C_INT.withName("srcRGB"),
        NVG.C_INT.withName("dstRGB"),
        NVG.C_INT.withName("srcAlpha"),
        NVG.C_INT.withName("dstAlpha")
    ).withName("NVGcompositeOperationState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt srcRGB$LAYOUT = (OfInt)$LAYOUT.select(groupElement("srcRGB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int srcRGB
     * }
     */
    public static final OfInt srcRGB$layout() {
        return srcRGB$LAYOUT;
    }

    private static final long srcRGB$OFFSET = $LAYOUT.byteOffset(groupElement("srcRGB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int srcRGB
     * }
     */
    public static final long srcRGB$offset() {
        return srcRGB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int srcRGB
     * }
     */
    public static int srcRGB(MemorySegment struct) {
        return struct.get(srcRGB$LAYOUT, srcRGB$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int srcRGB
     * }
     */
    public static void srcRGB(MemorySegment struct, int fieldValue) {
        struct.set(srcRGB$LAYOUT, srcRGB$OFFSET, fieldValue);
    }

    private static final OfInt dstRGB$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dstRGB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dstRGB
     * }
     */
    public static final OfInt dstRGB$layout() {
        return dstRGB$LAYOUT;
    }

    private static final long dstRGB$OFFSET = $LAYOUT.byteOffset(groupElement("dstRGB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dstRGB
     * }
     */
    public static final long dstRGB$offset() {
        return dstRGB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dstRGB
     * }
     */
    public static int dstRGB(MemorySegment struct) {
        return struct.get(dstRGB$LAYOUT, dstRGB$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dstRGB
     * }
     */
    public static void dstRGB(MemorySegment struct, int fieldValue) {
        struct.set(dstRGB$LAYOUT, dstRGB$OFFSET, fieldValue);
    }

    private static final OfInt srcAlpha$LAYOUT = (OfInt)$LAYOUT.select(groupElement("srcAlpha"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int srcAlpha
     * }
     */
    public static final OfInt srcAlpha$layout() {
        return srcAlpha$LAYOUT;
    }

    private static final long srcAlpha$OFFSET = $LAYOUT.byteOffset(groupElement("srcAlpha"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int srcAlpha
     * }
     */
    public static final long srcAlpha$offset() {
        return srcAlpha$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int srcAlpha
     * }
     */
    public static int srcAlpha(MemorySegment struct) {
        return struct.get(srcAlpha$LAYOUT, srcAlpha$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int srcAlpha
     * }
     */
    public static void srcAlpha(MemorySegment struct, int fieldValue) {
        struct.set(srcAlpha$LAYOUT, srcAlpha$OFFSET, fieldValue);
    }

    private static final OfInt dstAlpha$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dstAlpha"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dstAlpha
     * }
     */
    public static final OfInt dstAlpha$layout() {
        return dstAlpha$LAYOUT;
    }

    private static final long dstAlpha$OFFSET = $LAYOUT.byteOffset(groupElement("dstAlpha"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dstAlpha
     * }
     */
    public static final long dstAlpha$offset() {
        return dstAlpha$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dstAlpha
     * }
     */
    public static int dstAlpha(MemorySegment struct) {
        return struct.get(dstAlpha$LAYOUT, dstAlpha$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dstAlpha
     * }
     */
    public static void dstAlpha(MemorySegment struct, int fieldValue) {
        struct.set(dstAlpha$LAYOUT, dstAlpha$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

