// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGcolor {
 *     union {
 *         float rgba[4];
 *         struct {
 *             float r;
 *             float g;
 *             float b;
 *             float a;
 *         };
 *     };
 * }
 * }
 */
public class NVGcolor {

    NVGcolor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.unionLayout(
            MemoryLayout.sequenceLayout(4, NVG.C_FLOAT).withName("rgba"),
            MemoryLayout.structLayout(
                NVG.C_FLOAT.withName("r"),
                NVG.C_FLOAT.withName("g"),
                NVG.C_FLOAT.withName("b"),
                NVG.C_FLOAT.withName("a")
            ).withName("$anon$38:3")
        ).withName("$anon$36:2")
    ).withName("NVGcolor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout rgba$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("$anon$36:2"), groupElement("rgba"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float rgba[4]
     * }
     */
    public static final SequenceLayout rgba$layout() {
        return rgba$LAYOUT;
    }

    private static final long rgba$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$36:2"), groupElement("rgba"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float rgba[4]
     * }
     */
    public static final long rgba$offset() {
        return rgba$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float rgba[4]
     * }
     */
    public static MemorySegment rgba(MemorySegment struct) {
        return struct.asSlice(rgba$OFFSET, rgba$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float rgba[4]
     * }
     */
    public static void rgba(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, rgba$OFFSET, rgba$LAYOUT.byteSize());
    }

    private static long[] rgba$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float rgba[4]
     * }
     */
    public static long[] rgba$dimensions() {
        return rgba$DIMS;
    }
    private static final VarHandle rgba$ELEM_HANDLE = rgba$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float rgba[4]
     * }
     */
    public static float rgba(MemorySegment struct, long index0) {
        return (float)rgba$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float rgba[4]
     * }
     */
    public static void rgba(MemorySegment struct, long index0, float fieldValue) {
        rgba$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfFloat r$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("r"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float r
     * }
     */
    public static final OfFloat r$layout() {
        return r$LAYOUT;
    }

    private static final long r$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("r"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float r
     * }
     */
    public static final long r$offset() {
        return r$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float r
     * }
     */
    public static float r(MemorySegment struct) {
        return struct.get(r$LAYOUT, r$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float r
     * }
     */
    public static void r(MemorySegment struct, float fieldValue) {
        struct.set(r$LAYOUT, r$OFFSET, fieldValue);
    }

    private static final OfFloat g$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("g"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float g
     * }
     */
    public static final OfFloat g$layout() {
        return g$LAYOUT;
    }

    private static final long g$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("g"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float g
     * }
     */
    public static final long g$offset() {
        return g$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float g
     * }
     */
    public static float g(MemorySegment struct) {
        return struct.get(g$LAYOUT, g$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float g
     * }
     */
    public static void g(MemorySegment struct, float fieldValue) {
        struct.set(g$LAYOUT, g$OFFSET, fieldValue);
    }

    private static final OfFloat b$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("b"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float b
     * }
     */
    public static final OfFloat b$layout() {
        return b$LAYOUT;
    }

    private static final long b$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("b"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float b
     * }
     */
    public static final long b$offset() {
        return b$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float b
     * }
     */
    public static float b(MemorySegment struct) {
        return struct.get(b$LAYOUT, b$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float b
     * }
     */
    public static void b(MemorySegment struct, float fieldValue) {
        struct.set(b$LAYOUT, b$OFFSET, fieldValue);
    }

    private static final OfFloat a$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("a"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float a
     * }
     */
    public static final OfFloat a$layout() {
        return a$LAYOUT;
    }

    private static final long a$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$36:2"), groupElement("$anon$38:3"), groupElement("a"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float a
     * }
     */
    public static final long a$offset() {
        return a$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float a
     * }
     */
    public static float a(MemorySegment struct) {
        return struct.get(a$LAYOUT, a$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float a
     * }
     */
    public static void a(MemorySegment struct, float fieldValue) {
        struct.set(a$LAYOUT, a$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

