// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGglyphPosition {
 *     const char *str;
 *     float x;
 *     float minx;
 *     float maxx;
 * }
 * }
 */
public class NVGglyphPosition {

    NVGglyphPosition() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NVG.C_POINTER.withName("str"),
        NVG.C_FLOAT.withName("x"),
        NVG.C_FLOAT.withName("minx"),
        NVG.C_FLOAT.withName("maxx"),
        MemoryLayout.paddingLayout(4)
    ).withName("NVGglyphPosition");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout str$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("str"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *str
     * }
     */
    public static final AddressLayout str$layout() {
        return str$LAYOUT;
    }

    private static final long str$OFFSET = $LAYOUT.byteOffset(groupElement("str"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *str
     * }
     */
    public static final long str$offset() {
        return str$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *str
     * }
     */
    public static MemorySegment str(MemorySegment struct) {
        return struct.get(str$LAYOUT, str$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *str
     * }
     */
    public static void str(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(str$LAYOUT, str$OFFSET, fieldValue);
    }

    private static final OfFloat x$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float x
     * }
     */
    public static final OfFloat x$layout() {
        return x$LAYOUT;
    }

    private static final long x$OFFSET = $LAYOUT.byteOffset(groupElement("x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float x
     * }
     */
    public static final long x$offset() {
        return x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float x
     * }
     */
    public static float x(MemorySegment struct) {
        return struct.get(x$LAYOUT, x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float x
     * }
     */
    public static void x(MemorySegment struct, float fieldValue) {
        struct.set(x$LAYOUT, x$OFFSET, fieldValue);
    }

    private static final OfFloat minx$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("minx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static final OfFloat minx$layout() {
        return minx$LAYOUT;
    }

    private static final long minx$OFFSET = $LAYOUT.byteOffset(groupElement("minx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static final long minx$offset() {
        return minx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static float minx(MemorySegment struct) {
        return struct.get(minx$LAYOUT, minx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static void minx(MemorySegment struct, float fieldValue) {
        struct.set(minx$LAYOUT, minx$OFFSET, fieldValue);
    }

    private static final OfFloat maxx$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static final OfFloat maxx$layout() {
        return maxx$LAYOUT;
    }

    private static final long maxx$OFFSET = $LAYOUT.byteOffset(groupElement("maxx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static final long maxx$offset() {
        return maxx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static float maxx(MemorySegment struct) {
        return struct.get(maxx$LAYOUT, maxx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static void maxx(MemorySegment struct, float fieldValue) {
        struct.set(maxx$LAYOUT, maxx$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

