// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGpath {
 *     int first;
 *     int count;
 *     unsigned char closed;
 *     int nbevel;
 *     NVGvertex *fill;
 *     int nfill;
 *     NVGvertex *stroke;
 *     int nstroke;
 *     int winding;
 *     int convex;
 * }
 * }
 */
public class NVGpath {

    NVGpath() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NVG.C_INT.withName("first"),
        NVG.C_INT.withName("count"),
        NVG.C_CHAR.withName("closed"),
        MemoryLayout.paddingLayout(3),
        NVG.C_INT.withName("nbevel"),
        NVG.C_POINTER.withName("fill"),
        NVG.C_INT.withName("nfill"),
        MemoryLayout.paddingLayout(4),
        NVG.C_POINTER.withName("stroke"),
        NVG.C_INT.withName("nstroke"),
        NVG.C_INT.withName("winding"),
        NVG.C_INT.withName("convex"),
        MemoryLayout.paddingLayout(4)
    ).withName("NVGpath");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt first$LAYOUT = (OfInt)$LAYOUT.select(groupElement("first"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int first
     * }
     */
    public static final OfInt first$layout() {
        return first$LAYOUT;
    }

    private static final long first$OFFSET = $LAYOUT.byteOffset(groupElement("first"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int first
     * }
     */
    public static final long first$offset() {
        return first$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int first
     * }
     */
    public static int first(MemorySegment struct) {
        return struct.get(first$LAYOUT, first$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int first
     * }
     */
    public static void first(MemorySegment struct, int fieldValue) {
        struct.set(first$LAYOUT, first$OFFSET, fieldValue);
    }

    private static final OfInt count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static final OfInt count$layout() {
        return count$LAYOUT;
    }

    private static final long count$OFFSET = $LAYOUT.byteOffset(groupElement("count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static final long count$offset() {
        return count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static int count(MemorySegment struct) {
        return struct.get(count$LAYOUT, count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static void count(MemorySegment struct, int fieldValue) {
        struct.set(count$LAYOUT, count$OFFSET, fieldValue);
    }

    private static final OfByte closed$LAYOUT = (OfByte)$LAYOUT.select(groupElement("closed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char closed
     * }
     */
    public static final OfByte closed$layout() {
        return closed$LAYOUT;
    }

    private static final long closed$OFFSET = $LAYOUT.byteOffset(groupElement("closed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char closed
     * }
     */
    public static final long closed$offset() {
        return closed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char closed
     * }
     */
    public static byte closed(MemorySegment struct) {
        return struct.get(closed$LAYOUT, closed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char closed
     * }
     */
    public static void closed(MemorySegment struct, byte fieldValue) {
        struct.set(closed$LAYOUT, closed$OFFSET, fieldValue);
    }

    private static final OfInt nbevel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nbevel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nbevel
     * }
     */
    public static final OfInt nbevel$layout() {
        return nbevel$LAYOUT;
    }

    private static final long nbevel$OFFSET = $LAYOUT.byteOffset(groupElement("nbevel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nbevel
     * }
     */
    public static final long nbevel$offset() {
        return nbevel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nbevel
     * }
     */
    public static int nbevel(MemorySegment struct) {
        return struct.get(nbevel$LAYOUT, nbevel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nbevel
     * }
     */
    public static void nbevel(MemorySegment struct, int fieldValue) {
        struct.set(nbevel$LAYOUT, nbevel$OFFSET, fieldValue);
    }

    private static final AddressLayout fill$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * NVGvertex *fill
     * }
     */
    public static final AddressLayout fill$layout() {
        return fill$LAYOUT;
    }

    private static final long fill$OFFSET = $LAYOUT.byteOffset(groupElement("fill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * NVGvertex *fill
     * }
     */
    public static final long fill$offset() {
        return fill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * NVGvertex *fill
     * }
     */
    public static MemorySegment fill(MemorySegment struct) {
        return struct.get(fill$LAYOUT, fill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * NVGvertex *fill
     * }
     */
    public static void fill(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fill$LAYOUT, fill$OFFSET, fieldValue);
    }

    private static final OfInt nfill$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nfill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nfill
     * }
     */
    public static final OfInt nfill$layout() {
        return nfill$LAYOUT;
    }

    private static final long nfill$OFFSET = $LAYOUT.byteOffset(groupElement("nfill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nfill
     * }
     */
    public static final long nfill$offset() {
        return nfill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nfill
     * }
     */
    public static int nfill(MemorySegment struct) {
        return struct.get(nfill$LAYOUT, nfill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nfill
     * }
     */
    public static void nfill(MemorySegment struct, int fieldValue) {
        struct.set(nfill$LAYOUT, nfill$OFFSET, fieldValue);
    }

    private static final AddressLayout stroke$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("stroke"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * NVGvertex *stroke
     * }
     */
    public static final AddressLayout stroke$layout() {
        return stroke$LAYOUT;
    }

    private static final long stroke$OFFSET = $LAYOUT.byteOffset(groupElement("stroke"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * NVGvertex *stroke
     * }
     */
    public static final long stroke$offset() {
        return stroke$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * NVGvertex *stroke
     * }
     */
    public static MemorySegment stroke(MemorySegment struct) {
        return struct.get(stroke$LAYOUT, stroke$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * NVGvertex *stroke
     * }
     */
    public static void stroke(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(stroke$LAYOUT, stroke$OFFSET, fieldValue);
    }

    private static final OfInt nstroke$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nstroke"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nstroke
     * }
     */
    public static final OfInt nstroke$layout() {
        return nstroke$LAYOUT;
    }

    private static final long nstroke$OFFSET = $LAYOUT.byteOffset(groupElement("nstroke"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nstroke
     * }
     */
    public static final long nstroke$offset() {
        return nstroke$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nstroke
     * }
     */
    public static int nstroke(MemorySegment struct) {
        return struct.get(nstroke$LAYOUT, nstroke$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nstroke
     * }
     */
    public static void nstroke(MemorySegment struct, int fieldValue) {
        struct.set(nstroke$LAYOUT, nstroke$OFFSET, fieldValue);
    }

    private static final OfInt winding$LAYOUT = (OfInt)$LAYOUT.select(groupElement("winding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int winding
     * }
     */
    public static final OfInt winding$layout() {
        return winding$LAYOUT;
    }

    private static final long winding$OFFSET = $LAYOUT.byteOffset(groupElement("winding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int winding
     * }
     */
    public static final long winding$offset() {
        return winding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int winding
     * }
     */
    public static int winding(MemorySegment struct) {
        return struct.get(winding$LAYOUT, winding$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int winding
     * }
     */
    public static void winding(MemorySegment struct, int fieldValue) {
        struct.set(winding$LAYOUT, winding$OFFSET, fieldValue);
    }

    private static final OfInt convex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("convex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int convex
     * }
     */
    public static final OfInt convex$layout() {
        return convex$LAYOUT;
    }

    private static final long convex$OFFSET = $LAYOUT.byteOffset(groupElement("convex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int convex
     * }
     */
    public static final long convex$offset() {
        return convex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int convex
     * }
     */
    public static int convex(MemorySegment struct) {
        return struct.get(convex$LAYOUT, convex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int convex
     * }
     */
    public static void convex(MemorySegment struct, int fieldValue) {
        struct.set(convex$LAYOUT, convex$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

