// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGpaint {
 *     float xform[6];
 *     float extent[2];
 *     float radius;
 *     float feather;
 *     NVGcolor innerColor;
 *     NVGcolor outerColor;
 *     int image;
 * }
 * }
 */
public class NVGpaint {

    NVGpaint() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(6, NVG.C_FLOAT).withName("xform"),
        MemoryLayout.sequenceLayout(2, NVG.C_FLOAT).withName("extent"),
        NVG.C_FLOAT.withName("radius"),
        NVG.C_FLOAT.withName("feather"),
        NVGcolor.layout().withName("innerColor"),
        NVGcolor.layout().withName("outerColor"),
        NVG.C_INT.withName("image")
    ).withName("NVGpaint");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout xform$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("xform"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static final SequenceLayout xform$layout() {
        return xform$LAYOUT;
    }

    private static final long xform$OFFSET = $LAYOUT.byteOffset(groupElement("xform"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static final long xform$offset() {
        return xform$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static MemorySegment xform(MemorySegment struct) {
        return struct.asSlice(xform$OFFSET, xform$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static void xform(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, xform$OFFSET, xform$LAYOUT.byteSize());
    }

    private static long[] xform$DIMS = { 6 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static long[] xform$dimensions() {
        return xform$DIMS;
    }
    private static final VarHandle xform$ELEM_HANDLE = xform$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static float xform(MemorySegment struct, long index0) {
        return (float)xform$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static void xform(MemorySegment struct, long index0, float fieldValue) {
        xform$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout extent$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("extent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static final SequenceLayout extent$layout() {
        return extent$LAYOUT;
    }

    private static final long extent$OFFSET = $LAYOUT.byteOffset(groupElement("extent"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static final long extent$offset() {
        return extent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static MemorySegment extent(MemorySegment struct) {
        return struct.asSlice(extent$OFFSET, extent$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static void extent(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, extent$OFFSET, extent$LAYOUT.byteSize());
    }

    private static long[] extent$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static long[] extent$dimensions() {
        return extent$DIMS;
    }
    private static final VarHandle extent$ELEM_HANDLE = extent$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static float extent(MemorySegment struct, long index0) {
        return (float)extent$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static void extent(MemorySegment struct, long index0, float fieldValue) {
        extent$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfFloat radius$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("radius"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static final OfFloat radius$layout() {
        return radius$LAYOUT;
    }

    private static final long radius$OFFSET = $LAYOUT.byteOffset(groupElement("radius"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static final long radius$offset() {
        return radius$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static float radius(MemorySegment struct) {
        return struct.get(radius$LAYOUT, radius$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float radius
     * }
     */
    public static void radius(MemorySegment struct, float fieldValue) {
        struct.set(radius$LAYOUT, radius$OFFSET, fieldValue);
    }

    private static final OfFloat feather$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("feather"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float feather
     * }
     */
    public static final OfFloat feather$layout() {
        return feather$LAYOUT;
    }

    private static final long feather$OFFSET = $LAYOUT.byteOffset(groupElement("feather"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float feather
     * }
     */
    public static final long feather$offset() {
        return feather$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float feather
     * }
     */
    public static float feather(MemorySegment struct) {
        return struct.get(feather$LAYOUT, feather$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float feather
     * }
     */
    public static void feather(MemorySegment struct, float fieldValue) {
        struct.set(feather$LAYOUT, feather$OFFSET, fieldValue);
    }

    private static final GroupLayout innerColor$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("innerColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * NVGcolor innerColor
     * }
     */
    public static final GroupLayout innerColor$layout() {
        return innerColor$LAYOUT;
    }

    private static final long innerColor$OFFSET = $LAYOUT.byteOffset(groupElement("innerColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * NVGcolor innerColor
     * }
     */
    public static final long innerColor$offset() {
        return innerColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * NVGcolor innerColor
     * }
     */
    public static MemorySegment innerColor(MemorySegment struct) {
        return struct.asSlice(innerColor$OFFSET, innerColor$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * NVGcolor innerColor
     * }
     */
    public static void innerColor(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, innerColor$OFFSET, innerColor$LAYOUT.byteSize());
    }

    private static final GroupLayout outerColor$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("outerColor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * NVGcolor outerColor
     * }
     */
    public static final GroupLayout outerColor$layout() {
        return outerColor$LAYOUT;
    }

    private static final long outerColor$OFFSET = $LAYOUT.byteOffset(groupElement("outerColor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * NVGcolor outerColor
     * }
     */
    public static final long outerColor$offset() {
        return outerColor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * NVGcolor outerColor
     * }
     */
    public static MemorySegment outerColor(MemorySegment struct) {
        return struct.asSlice(outerColor$OFFSET, outerColor$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * NVGcolor outerColor
     * }
     */
    public static void outerColor(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, outerColor$OFFSET, outerColor$LAYOUT.byteSize());
    }

    private static final OfInt image$LAYOUT = (OfInt)$LAYOUT.select(groupElement("image"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int image
     * }
     */
    public static final OfInt image$layout() {
        return image$LAYOUT;
    }

    private static final long image$OFFSET = $LAYOUT.byteOffset(groupElement("image"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int image
     * }
     */
    public static final long image$offset() {
        return image$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int image
     * }
     */
    public static int image(MemorySegment struct) {
        return struct.get(image$LAYOUT, image$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int image
     * }
     */
    public static void image(MemorySegment struct, int fieldValue) {
        struct.set(image$LAYOUT, image$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

