// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGparams {
 *     void *userPtr;
 *     int edgeAntiAlias;
 *     int (*renderCreate)(void *);
 *     int (*renderCreateTexture)(void *, int, int, int, int, const unsigned char *);
 *     int (*renderDeleteTexture)(void *, int);
 *     int (*renderUpdateTexture)(void *, int, int, int, int, int, const unsigned char *);
 *     int (*renderGetTextureSize)(void *, int, int *, int *);
 *     void (*renderViewport)(void *, float, float, float);
 *     void (*renderCancel)(void *);
 *     void (*renderFlush)(void *);
 *     void (*renderFill)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, const float *, const NVGpath *, int);
 *     void (*renderStroke)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, float, const NVGpath *, int);
 *     void (*renderTriangles)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, const NVGvertex *, int, float);
 *     void (*renderDelete)(void *);
 * }
 * }
 */
public class NVGparams {

    NVGparams() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NVG.C_POINTER.withName("userPtr"),
        NVG.C_INT.withName("edgeAntiAlias"),
        MemoryLayout.paddingLayout(4),
        NVG.C_POINTER.withName("renderCreate"),
        NVG.C_POINTER.withName("renderCreateTexture"),
        NVG.C_POINTER.withName("renderDeleteTexture"),
        NVG.C_POINTER.withName("renderUpdateTexture"),
        NVG.C_POINTER.withName("renderGetTextureSize"),
        NVG.C_POINTER.withName("renderViewport"),
        NVG.C_POINTER.withName("renderCancel"),
        NVG.C_POINTER.withName("renderFlush"),
        NVG.C_POINTER.withName("renderFill"),
        NVG.C_POINTER.withName("renderStroke"),
        NVG.C_POINTER.withName("renderTriangles"),
        NVG.C_POINTER.withName("renderDelete")
    ).withName("NVGparams");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout userPtr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userPtr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userPtr
     * }
     */
    public static final AddressLayout userPtr$layout() {
        return userPtr$LAYOUT;
    }

    private static final long userPtr$OFFSET = $LAYOUT.byteOffset(groupElement("userPtr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userPtr
     * }
     */
    public static final long userPtr$offset() {
        return userPtr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userPtr
     * }
     */
    public static MemorySegment userPtr(MemorySegment struct) {
        return struct.get(userPtr$LAYOUT, userPtr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userPtr
     * }
     */
    public static void userPtr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userPtr$LAYOUT, userPtr$OFFSET, fieldValue);
    }

    private static final OfInt edgeAntiAlias$LAYOUT = (OfInt)$LAYOUT.select(groupElement("edgeAntiAlias"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int edgeAntiAlias
     * }
     */
    public static final OfInt edgeAntiAlias$layout() {
        return edgeAntiAlias$LAYOUT;
    }

    private static final long edgeAntiAlias$OFFSET = $LAYOUT.byteOffset(groupElement("edgeAntiAlias"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int edgeAntiAlias
     * }
     */
    public static final long edgeAntiAlias$offset() {
        return edgeAntiAlias$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int edgeAntiAlias
     * }
     */
    public static int edgeAntiAlias(MemorySegment struct) {
        return struct.get(edgeAntiAlias$LAYOUT, edgeAntiAlias$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int edgeAntiAlias
     * }
     */
    public static void edgeAntiAlias(MemorySegment struct, int fieldValue) {
        struct.set(edgeAntiAlias$LAYOUT, edgeAntiAlias$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*renderCreate)(void *)
     * }
     */
    public final static class renderCreate {

        private renderCreate() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NVG.C_INT,
            NVG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderCreate.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderCreate.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderCreate$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderCreate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*renderCreate)(void *)
     * }
     */
    public static final AddressLayout renderCreate$layout() {
        return renderCreate$LAYOUT;
    }

    private static final long renderCreate$OFFSET = $LAYOUT.byteOffset(groupElement("renderCreate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*renderCreate)(void *)
     * }
     */
    public static final long renderCreate$offset() {
        return renderCreate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*renderCreate)(void *)
     * }
     */
    public static MemorySegment renderCreate(MemorySegment struct) {
        return struct.get(renderCreate$LAYOUT, renderCreate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*renderCreate)(void *)
     * }
     */
    public static void renderCreate(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderCreate$LAYOUT, renderCreate$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*renderCreateTexture)(void *, int, int, int, int, const unsigned char *)
     * }
     */
    public final static class renderCreateTexture {

        private renderCreateTexture() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, int _x3, int _x4, MemorySegment _x5);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NVG.C_INT,
            NVG.C_POINTER,
            NVG.C_INT,
            NVG.C_INT,
            NVG.C_INT,
            NVG.C_INT,
            NVG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderCreateTexture.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderCreateTexture.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, int _x3, int _x4, MemorySegment _x5) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderCreateTexture$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderCreateTexture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*renderCreateTexture)(void *, int, int, int, int, const unsigned char *)
     * }
     */
    public static final AddressLayout renderCreateTexture$layout() {
        return renderCreateTexture$LAYOUT;
    }

    private static final long renderCreateTexture$OFFSET = $LAYOUT.byteOffset(groupElement("renderCreateTexture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*renderCreateTexture)(void *, int, int, int, int, const unsigned char *)
     * }
     */
    public static final long renderCreateTexture$offset() {
        return renderCreateTexture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*renderCreateTexture)(void *, int, int, int, int, const unsigned char *)
     * }
     */
    public static MemorySegment renderCreateTexture(MemorySegment struct) {
        return struct.get(renderCreateTexture$LAYOUT, renderCreateTexture$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*renderCreateTexture)(void *, int, int, int, int, const unsigned char *)
     * }
     */
    public static void renderCreateTexture(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderCreateTexture$LAYOUT, renderCreateTexture$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*renderDeleteTexture)(void *, int)
     * }
     */
    public final static class renderDeleteTexture {

        private renderDeleteTexture() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NVG.C_INT,
            NVG.C_POINTER,
            NVG.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderDeleteTexture.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderDeleteTexture.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderDeleteTexture$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderDeleteTexture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*renderDeleteTexture)(void *, int)
     * }
     */
    public static final AddressLayout renderDeleteTexture$layout() {
        return renderDeleteTexture$LAYOUT;
    }

    private static final long renderDeleteTexture$OFFSET = $LAYOUT.byteOffset(groupElement("renderDeleteTexture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*renderDeleteTexture)(void *, int)
     * }
     */
    public static final long renderDeleteTexture$offset() {
        return renderDeleteTexture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*renderDeleteTexture)(void *, int)
     * }
     */
    public static MemorySegment renderDeleteTexture(MemorySegment struct) {
        return struct.get(renderDeleteTexture$LAYOUT, renderDeleteTexture$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*renderDeleteTexture)(void *, int)
     * }
     */
    public static void renderDeleteTexture(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderDeleteTexture$LAYOUT, renderDeleteTexture$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*renderUpdateTexture)(void *, int, int, int, int, int, const unsigned char *)
     * }
     */
    public final static class renderUpdateTexture {

        private renderUpdateTexture() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, int _x3, int _x4, int _x5, MemorySegment _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NVG.C_INT,
            NVG.C_POINTER,
            NVG.C_INT,
            NVG.C_INT,
            NVG.C_INT,
            NVG.C_INT,
            NVG.C_INT,
            NVG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderUpdateTexture.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderUpdateTexture.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, int _x2, int _x3, int _x4, int _x5, MemorySegment _x6) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderUpdateTexture$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderUpdateTexture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*renderUpdateTexture)(void *, int, int, int, int, int, const unsigned char *)
     * }
     */
    public static final AddressLayout renderUpdateTexture$layout() {
        return renderUpdateTexture$LAYOUT;
    }

    private static final long renderUpdateTexture$OFFSET = $LAYOUT.byteOffset(groupElement("renderUpdateTexture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*renderUpdateTexture)(void *, int, int, int, int, int, const unsigned char *)
     * }
     */
    public static final long renderUpdateTexture$offset() {
        return renderUpdateTexture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*renderUpdateTexture)(void *, int, int, int, int, int, const unsigned char *)
     * }
     */
    public static MemorySegment renderUpdateTexture(MemorySegment struct) {
        return struct.get(renderUpdateTexture$LAYOUT, renderUpdateTexture$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*renderUpdateTexture)(void *, int, int, int, int, int, const unsigned char *)
     * }
     */
    public static void renderUpdateTexture(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderUpdateTexture$LAYOUT, renderUpdateTexture$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*renderGetTextureSize)(void *, int, int *, int *)
     * }
     */
    public final static class renderGetTextureSize {

        private renderGetTextureSize() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, MemorySegment _x2, MemorySegment _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            NVG.C_INT,
            NVG.C_POINTER,
            NVG.C_INT,
            NVG.C_POINTER,
            NVG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderGetTextureSize.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderGetTextureSize.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, int _x1, MemorySegment _x2, MemorySegment _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderGetTextureSize$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderGetTextureSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*renderGetTextureSize)(void *, int, int *, int *)
     * }
     */
    public static final AddressLayout renderGetTextureSize$layout() {
        return renderGetTextureSize$LAYOUT;
    }

    private static final long renderGetTextureSize$OFFSET = $LAYOUT.byteOffset(groupElement("renderGetTextureSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*renderGetTextureSize)(void *, int, int *, int *)
     * }
     */
    public static final long renderGetTextureSize$offset() {
        return renderGetTextureSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*renderGetTextureSize)(void *, int, int *, int *)
     * }
     */
    public static MemorySegment renderGetTextureSize(MemorySegment struct) {
        return struct.get(renderGetTextureSize$LAYOUT, renderGetTextureSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*renderGetTextureSize)(void *, int, int *, int *)
     * }
     */
    public static void renderGetTextureSize(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderGetTextureSize$LAYOUT, renderGetTextureSize$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*renderViewport)(void *, float, float, float)
     * }
     */
    public final static class renderViewport {

        private renderViewport() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, float _x1, float _x2, float _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            NVG.C_POINTER,
            NVG.C_FLOAT,
            NVG.C_FLOAT,
            NVG.C_FLOAT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderViewport.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderViewport.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, float _x1, float _x2, float _x3) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderViewport$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderViewport"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*renderViewport)(void *, float, float, float)
     * }
     */
    public static final AddressLayout renderViewport$layout() {
        return renderViewport$LAYOUT;
    }

    private static final long renderViewport$OFFSET = $LAYOUT.byteOffset(groupElement("renderViewport"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*renderViewport)(void *, float, float, float)
     * }
     */
    public static final long renderViewport$offset() {
        return renderViewport$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*renderViewport)(void *, float, float, float)
     * }
     */
    public static MemorySegment renderViewport(MemorySegment struct) {
        return struct.get(renderViewport$LAYOUT, renderViewport$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*renderViewport)(void *, float, float, float)
     * }
     */
    public static void renderViewport(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderViewport$LAYOUT, renderViewport$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*renderCancel)(void *)
     * }
     */
    public final static class renderCancel {

        private renderCancel() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            NVG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderCancel.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderCancel.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderCancel$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderCancel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*renderCancel)(void *)
     * }
     */
    public static final AddressLayout renderCancel$layout() {
        return renderCancel$LAYOUT;
    }

    private static final long renderCancel$OFFSET = $LAYOUT.byteOffset(groupElement("renderCancel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*renderCancel)(void *)
     * }
     */
    public static final long renderCancel$offset() {
        return renderCancel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*renderCancel)(void *)
     * }
     */
    public static MemorySegment renderCancel(MemorySegment struct) {
        return struct.get(renderCancel$LAYOUT, renderCancel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*renderCancel)(void *)
     * }
     */
    public static void renderCancel(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderCancel$LAYOUT, renderCancel$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*renderFlush)(void *)
     * }
     */
    public final static class renderFlush {

        private renderFlush() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            NVG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderFlush.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderFlush.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderFlush$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderFlush"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*renderFlush)(void *)
     * }
     */
    public static final AddressLayout renderFlush$layout() {
        return renderFlush$LAYOUT;
    }

    private static final long renderFlush$OFFSET = $LAYOUT.byteOffset(groupElement("renderFlush"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*renderFlush)(void *)
     * }
     */
    public static final long renderFlush$offset() {
        return renderFlush$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*renderFlush)(void *)
     * }
     */
    public static MemorySegment renderFlush(MemorySegment struct) {
        return struct.get(renderFlush$LAYOUT, renderFlush$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*renderFlush)(void *)
     * }
     */
    public static void renderFlush(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderFlush$LAYOUT, renderFlush$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*renderFill)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, const float *, const NVGpath *, int)
     * }
     */
    public final static class renderFill {

        private renderFill() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, float _x4, MemorySegment _x5, MemorySegment _x6, int _x7);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            NVG.C_POINTER,
            NVG.C_POINTER,
            NVGcompositeOperationState.layout(),
            NVG.C_POINTER,
            NVG.C_FLOAT,
            NVG.C_POINTER,
            NVG.C_POINTER,
            NVG.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderFill.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderFill.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, float _x4, MemorySegment _x5, MemorySegment _x6, int _x7) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6, _x7);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderFill$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderFill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*renderFill)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, const float *, const NVGpath *, int)
     * }
     */
    public static final AddressLayout renderFill$layout() {
        return renderFill$LAYOUT;
    }

    private static final long renderFill$OFFSET = $LAYOUT.byteOffset(groupElement("renderFill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*renderFill)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, const float *, const NVGpath *, int)
     * }
     */
    public static final long renderFill$offset() {
        return renderFill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*renderFill)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, const float *, const NVGpath *, int)
     * }
     */
    public static MemorySegment renderFill(MemorySegment struct) {
        return struct.get(renderFill$LAYOUT, renderFill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*renderFill)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, const float *, const NVGpath *, int)
     * }
     */
    public static void renderFill(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderFill$LAYOUT, renderFill$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*renderStroke)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, float, const NVGpath *, int)
     * }
     */
    public final static class renderStroke {

        private renderStroke() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, float _x4, float _x5, MemorySegment _x6, int _x7);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            NVG.C_POINTER,
            NVG.C_POINTER,
            NVGcompositeOperationState.layout(),
            NVG.C_POINTER,
            NVG.C_FLOAT,
            NVG.C_FLOAT,
            NVG.C_POINTER,
            NVG.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderStroke.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderStroke.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, float _x4, float _x5, MemorySegment _x6, int _x7) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6, _x7);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderStroke$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderStroke"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*renderStroke)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, float, const NVGpath *, int)
     * }
     */
    public static final AddressLayout renderStroke$layout() {
        return renderStroke$LAYOUT;
    }

    private static final long renderStroke$OFFSET = $LAYOUT.byteOffset(groupElement("renderStroke"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*renderStroke)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, float, const NVGpath *, int)
     * }
     */
    public static final long renderStroke$offset() {
        return renderStroke$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*renderStroke)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, float, const NVGpath *, int)
     * }
     */
    public static MemorySegment renderStroke(MemorySegment struct) {
        return struct.get(renderStroke$LAYOUT, renderStroke$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*renderStroke)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, float, float, const NVGpath *, int)
     * }
     */
    public static void renderStroke(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderStroke$LAYOUT, renderStroke$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*renderTriangles)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, const NVGvertex *, int, float)
     * }
     */
    public final static class renderTriangles {

        private renderTriangles() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4, int _x5, float _x6);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            NVG.C_POINTER,
            NVG.C_POINTER,
            NVGcompositeOperationState.layout(),
            NVG.C_POINTER,
            NVG.C_POINTER,
            NVG.C_INT,
            NVG.C_FLOAT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderTriangles.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderTriangles.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4, int _x5, float _x6) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderTriangles$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderTriangles"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*renderTriangles)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, const NVGvertex *, int, float)
     * }
     */
    public static final AddressLayout renderTriangles$layout() {
        return renderTriangles$LAYOUT;
    }

    private static final long renderTriangles$OFFSET = $LAYOUT.byteOffset(groupElement("renderTriangles"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*renderTriangles)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, const NVGvertex *, int, float)
     * }
     */
    public static final long renderTriangles$offset() {
        return renderTriangles$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*renderTriangles)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, const NVGvertex *, int, float)
     * }
     */
    public static MemorySegment renderTriangles(MemorySegment struct) {
        return struct.get(renderTriangles$LAYOUT, renderTriangles$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*renderTriangles)(void *, NVGpaint *, NVGcompositeOperationState, NVGscissor *, const NVGvertex *, int, float)
     * }
     */
    public static void renderTriangles(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderTriangles$LAYOUT, renderTriangles$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*renderDelete)(void *)
     * }
     */
    public final static class renderDelete {

        private renderDelete() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            NVG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = NVG.upcallHandle(renderDelete.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(renderDelete.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout renderDelete$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("renderDelete"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*renderDelete)(void *)
     * }
     */
    public static final AddressLayout renderDelete$layout() {
        return renderDelete$LAYOUT;
    }

    private static final long renderDelete$OFFSET = $LAYOUT.byteOffset(groupElement("renderDelete"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*renderDelete)(void *)
     * }
     */
    public static final long renderDelete$offset() {
        return renderDelete$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*renderDelete)(void *)
     * }
     */
    public static MemorySegment renderDelete(MemorySegment struct) {
        return struct.get(renderDelete$LAYOUT, renderDelete$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*renderDelete)(void *)
     * }
     */
    public static void renderDelete(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(renderDelete$LAYOUT, renderDelete$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

