// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGscissor {
 *     float xform[6];
 *     float extent[2];
 * }
 * }
 */
public class NVGscissor {

    NVGscissor() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(6, NVG.C_FLOAT).withName("xform"),
        MemoryLayout.sequenceLayout(2, NVG.C_FLOAT).withName("extent")
    ).withName("NVGscissor");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout xform$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("xform"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static final SequenceLayout xform$layout() {
        return xform$LAYOUT;
    }

    private static final long xform$OFFSET = $LAYOUT.byteOffset(groupElement("xform"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static final long xform$offset() {
        return xform$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static MemorySegment xform(MemorySegment struct) {
        return struct.asSlice(xform$OFFSET, xform$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static void xform(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, xform$OFFSET, xform$LAYOUT.byteSize());
    }

    private static long[] xform$DIMS = { 6 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static long[] xform$dimensions() {
        return xform$DIMS;
    }
    private static final VarHandle xform$ELEM_HANDLE = xform$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static float xform(MemorySegment struct, long index0) {
        return (float)xform$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float xform[6]
     * }
     */
    public static void xform(MemorySegment struct, long index0, float fieldValue) {
        xform$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout extent$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("extent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static final SequenceLayout extent$layout() {
        return extent$LAYOUT;
    }

    private static final long extent$OFFSET = $LAYOUT.byteOffset(groupElement("extent"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static final long extent$offset() {
        return extent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static MemorySegment extent(MemorySegment struct) {
        return struct.asSlice(extent$OFFSET, extent$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static void extent(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, extent$OFFSET, extent$LAYOUT.byteSize());
    }

    private static long[] extent$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static long[] extent$dimensions() {
        return extent$DIMS;
    }
    private static final VarHandle extent$ELEM_HANDLE = extent$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static float extent(MemorySegment struct, long index0) {
        return (float)extent$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float extent[2]
     * }
     */
    public static void extent(MemorySegment struct, long index0, float fieldValue) {
        extent$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

