// Generated by jextract

package com.fabcc.nanovg.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct NVGtextRow {
 *     const char *start;
 *     const char *end;
 *     const char *next;
 *     float width;
 *     float minx;
 *     float maxx;
 * }
 * }
 */
public class NVGtextRow {

    NVGtextRow() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        NVG.C_POINTER.withName("start"),
        NVG.C_POINTER.withName("end"),
        NVG.C_POINTER.withName("next"),
        NVG.C_FLOAT.withName("width"),
        NVG.C_FLOAT.withName("minx"),
        NVG.C_FLOAT.withName("maxx"),
        MemoryLayout.paddingLayout(4)
    ).withName("NVGtextRow");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout start$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *start
     * }
     */
    public static final AddressLayout start$layout() {
        return start$LAYOUT;
    }

    private static final long start$OFFSET = $LAYOUT.byteOffset(groupElement("start"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *start
     * }
     */
    public static final long start$offset() {
        return start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *start
     * }
     */
    public static MemorySegment start(MemorySegment struct) {
        return struct.get(start$LAYOUT, start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *start
     * }
     */
    public static void start(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(start$LAYOUT, start$OFFSET, fieldValue);
    }

    private static final AddressLayout end$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("end"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *end
     * }
     */
    public static final AddressLayout end$layout() {
        return end$LAYOUT;
    }

    private static final long end$OFFSET = $LAYOUT.byteOffset(groupElement("end"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *end
     * }
     */
    public static final long end$offset() {
        return end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *end
     * }
     */
    public static MemorySegment end(MemorySegment struct) {
        return struct.get(end$LAYOUT, end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *end
     * }
     */
    public static void end(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(end$LAYOUT, end$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    private static final OfFloat width$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float width
     * }
     */
    public static final OfFloat width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float width
     * }
     */
    public static float width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float width
     * }
     */
    public static void width(MemorySegment struct, float fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfFloat minx$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("minx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static final OfFloat minx$layout() {
        return minx$LAYOUT;
    }

    private static final long minx$OFFSET = $LAYOUT.byteOffset(groupElement("minx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static final long minx$offset() {
        return minx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static float minx(MemorySegment struct) {
        return struct.get(minx$LAYOUT, minx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float minx
     * }
     */
    public static void minx(MemorySegment struct, float fieldValue) {
        struct.set(minx$LAYOUT, minx$OFFSET, fieldValue);
    }

    private static final OfFloat maxx$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("maxx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static final OfFloat maxx$layout() {
        return maxx$LAYOUT;
    }

    private static final long maxx$OFFSET = $LAYOUT.byteOffset(groupElement("maxx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static final long maxx$offset() {
        return maxx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static float maxx(MemorySegment struct) {
        return struct.get(maxx$LAYOUT, maxx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxx
     * }
     */
    public static void maxx(MemorySegment struct, float fieldValue) {
        struct.set(maxx$LAYOUT, maxx$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

