// Generated by jextract

package com.fabcc.nanovg.example.glfwffm.lib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*GLLOGPROCREGAL)(GLenum, GLsizei, const GLchar *, void *)
 * }
 */
public final class GLLOGPROCREGAL {

    private GLLOGPROCREGAL() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(int stream, int length, MemorySegment message, MemorySegment context);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        GL.C_INT,
        GL.C_INT,
        GL.C_POINTER,
        GL.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = GL.upcallHandle(GLLOGPROCREGAL.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GLLOGPROCREGAL.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, int stream, int length, MemorySegment message, MemorySegment context) {
        try {
             DOWN$MH.invokeExact(funcPtr, stream, length, message, context);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

